apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-podinfo
  namespace: uat
  labels:
    helm.sh/chart: podinfo-6.5.4
    app.kubernetes.io/name: backend-podinfo
    app.kubernetes.io/version: "6.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - group: core
      kind: Service
      name: backend-podinfo
      port: 9898
  rules:
    - matches:
        - headers:
            - name: "x-request-id"
              value: jira-123
      backendRefs:
        - name: backend-podinfo
          namespace: jira-123
          port: 9898
    - backendRefs:
      - name: "backend-podinfo"
        namespace: uat
        port: 9898